# Generated by Django 4.2.7 on 2025-12-02 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('uptime', models.FloatField(default=100.0)),
                ('database_status', models.CharField(default='connected', max_length=50)),
                ('storage_usage', models.FloatField(default=0.0)),
                ('active_users', models.IntegerField(default=0)),
                ('api_response_time', models.FloatField(default=0.0)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health Records',
                'db_table': 'system_health',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['category', 'key'], 'verbose_name': 'System Configuration', 'verbose_name_plural': 'System Configurations'},
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('email', 'Email'), ('features', 'Features'), ('database', 'Database'), ('notifications', 'Notifications'), ('performance', 'Performance'), ('maintenance', 'Maintenance')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('text', 'Text'), ('password', 'Password'), ('secret', 'Secret'), ('select', 'Select'), ('json', 'JSON')], default='string', max_length=20),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical'), ('debug', 'Debug')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('system', 'System'), ('auth', 'Authentication'), ('database', 'Database'), ('api', 'API'), ('security', 'Security'), ('user', 'User Activity'), ('admin', 'Admin Action')], default='system', max_length=50)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='system_logs_level_5a2647_idx'), models.Index(fields=['category', 'created_at'], name='system_logs_categor_203279_idx'), models.Index(fields=['user', 'created_at'], name='system_logs_user_id_9ba726_idx')],
            },
        ),
    ]
