# Generated by Django 4.2.7 on 2025-11-30 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_certificate_course_coursemodule_learningpath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='sparkles', max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('estimated_duration_minutes', models.IntegerField(default=120)),
                ('category', models.CharField(default='Machine Learning', max_length=100)),
                ('prerequisites', models.JSONField(default=list)),
                ('starter_code_url', models.URLField(blank=True, null=True)),
                ('instructions_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_labs',
            },
        ),
        migrations.CreateModel(
            name='UserAILabProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('locked', 'Locked')], default='locked', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('code_submission', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='base.ailab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_lab_progress', to='base.user')),
            ],
            options={
                'db_table': 'user_ai_lab_progress',
                'unique_together': {('user', 'lab')},
            },
        ),
    ]
