# Generated by Django 4.2.7 on 2025-11-30 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ailab_userailabprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='trophy', max_length=50)),
                ('color', models.CharField(default='google-blue', max_length=20)),
                ('criteria_type', models.CharField(choices=[('courses_completed', 'Courses Completed'), ('modules_completed', 'Modules Completed'), ('learning_hours', 'Learning Hours'), ('streak_days', 'Streak Days'), ('labs_completed', 'Labs Completed'), ('certificates_earned', 'Certificates Earned')], max_length=50)),
                ('criteria_threshold', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='base.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='base.user')),
            ],
            options={
                'db_table': 'user_achievements',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
