# Generated by Django 4.2.7 on 2025-12-02 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='discussionreply',
            options={},
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='is_closed',
            new_name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='communityevent',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='communityevent',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='communityevent',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='communityevent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='is_solution',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='communityevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='base.course'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reported', 'Reported'), ('locked', 'Locked'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('webinar', 'Webinar'), ('meetup', 'Meetup'), ('study_group', 'Study Group'), ('guest_speaker', 'Guest Speaker')], max_length=50),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='max_attendees',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='communityevent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discussion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discussionreply',
            table=None,
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='base.communityevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
