# Generated by Django 4.2.7 on 2025-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_communityevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
