# Generated by Django 4.2.7 on 2025-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_coursemodule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
